#!/usr/bin/env bash
# test-plugin-json-input.sh - Validate plugin metadata input for issue #55.
#
# Usage: bash tests/test-plugin-json-input.sh
# Returns: exit 0 if all checks pass, exit 1 on failure

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PLUGIN_INPUT="$REPO_ROOT/src/plugin.json.in"

PASS=0
FAIL=0

pass() {
  echo "  ✓ $1"
  PASS=$((PASS + 1))
}

fail() {
  echo "  ✗ $1"
  FAIL=$((FAIL + 1))
}

echo "◆ Plugin Metadata Input Tests (issue #55)"
echo "┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄"

if [ -f "$PLUGIN_INPUT" ]; then
  pass "T1: src/plugin.json.in exists"
else
  fail "T1: src/plugin.json.in is missing"
fi

if python3 -m json.tool "$PLUGIN_INPUT" >/dev/null; then
  pass "T2: plugin.json.in is valid JSON input"
else
  fail "T2: plugin.json.in is not parseable JSON"
fi

for placeholder in \
  '${PLUGIN_SLUG}' \
  '${PLUGIN_VERSION}' \
  '${PLUGIN_NAME}' \
  '${PLUGIN_DESCRIPTION}' \
  '${PLUGIN_AUTHOR}'; do
  if grep -qF "$placeholder" "$PLUGIN_INPUT"; then
    pass "T3: placeholder present: $placeholder"
  else
    fail "T3: missing placeholder: $placeholder"
  fi
done

unknown_placeholders="$(grep -oE '\$\{[A-Z_]+\}' "$PLUGIN_INPUT" | sort -u | grep -vE '^\$\{PLUGIN_(SLUG|VERSION|NAME|DESCRIPTION|AUTHOR)\}$' || true)"
if [ -z "$unknown_placeholders" ]; then
  pass "T4: no unknown placeholder names"
else
  printf '%s\n' "$unknown_placeholders" | sed 's/^/    /'
  fail "T4: unknown placeholder names found"
fi

if grep -qF '"default_version": "0.12.0"' "$PLUGIN_INPUT"; then
  pass "T5: default_version is project version 0.12.0"
else
  fail "T5: default_version must be 0.12.0 until release bump"
fi

if grep -qF '"PLUGIN_SLUG": "idd"' "$PLUGIN_INPUT"; then
  pass "T6: PLUGIN_SLUG resolves to idd"
else
  fail "T6: PLUGIN_SLUG value must be idd"
fi

if grep -qF 'scripts/build.py substitution table' "$PLUGIN_INPUT"; then
  pass "T7: two-step placeholder change is documented"
else
  fail "T7: placeholder change rule must mention scripts/build.py table"
fi

if grep -qE '"skills"[[:space:]]*:' "$PLUGIN_INPUT"; then
  fail "T8: skill list must be generated by discovery, not authored here"
else
  pass "T8: no authored skills list in plugin.json.in"
fi

if find "$REPO_ROOT/src" -name 'plugin.json' -print | grep -q .; then
  find "$REPO_ROOT/src" -name 'plugin.json' -print | sed 's/^/    /'
  fail "T9: plugin metadata must not live in another source plugin.json"
else
  pass "T9: no duplicate source plugin.json metadata file"
fi

echo "┄┄┄┄┄┄┄┄┄┄┄┄"
echo "  Passed: $PASS"
echo "  Failed: $FAIL"

if [ "$FAIL" -gt 0 ]; then
  echo "  ✗ Plugin metadata input is incomplete"
  exit 1
fi

echo "  ✓ Plugin metadata input satisfies issue #55"
exit 0
